language: go
service_name: travis-pro
repo_token: BuV1p0nLOs0ExkmD50v8tErzBrzuCNi5T
services:
  - mongodb
go:
  - 1.10.x
  - 1.11.x
install:
  - go get .
  - go get github.com/smartystreets/goconvey
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
  - $GOPATH/bin/goveralls -service=travis-pro